AppCoder/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from AppCoder.views import logout_view

from AppCoder.views import (
    autos_view,
    autos_buscar_view,
    autos_todos_view,
    inicio_view,
    profesores_view,
    ### CRUD
    marcas_crud_delete_view,
    marcas_crud_read_view,
    profesores_crud_update_view,
    marca_view,
    AutoCreateView,
    AutoDetail,
    AutoDeleteView,
    AutoListView,
    AutoUpdateView,
    ### LOGIN
    login_view,
    registro_view,
    ### EDITAR PERFIL
    editar_perfil_view,
    crear_avatar_view,
    )


app_name = "AppCoder"

urlpatterns = [
    path("autos/", autos_view, name="autos"),
    path("autos/todos", autos_todos_view, name="autos-todos"),
    path("autos/buscar", autos_buscar_view, name="autos-buscar"),
    path("comisiones/", profesores_view),
    path("inicio/", inicio_view, name="inicio"),
    # CRUD
    path("marcas/", marca_view),
    path("marcas/lista", marcas_crud_read_view),
    path("profesores-eliminar/<profesor_email>/", marcas_crud_delete_view),
    path("profesores-editar/<profesor_email>/", profesores_crud_update_view),
    # CBV
    path("auto/list", AutoListView.as_view(), name="auto-list"),
    path("auto/new", AutoCreateView.as_view(), name="auto-create"),
    path("auto/<pk>", AutoDetail.as_view(), name="auto-detail"),
    path("auto/<pk>/update", AutoUpdateView.as_view(), name="auto-update"),
    path("auto/<pk>/delete", AutoDeleteView.as_view(), name="auto-delete"),
    # LOGIN
    path("registro", registro_view, name="registro"),
    path("login", login_view, name="login"),
    path('logout', logout_view, name='logout'),
    # EDITAR USUARIO
    path("editar-perfil", editar_perfil_view, name="editar-perfil"),
    path("crear-avatar", crear_avatar_view, name="crear-avatar"),
]
  

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("AppCoder/", include("AppCoder.urls")),
]

## CLASE 24
from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

AppCoder/models.py
from django.db import models

## CLASE 24
from django.contrib.auth.models import User

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"


class Marca(models.Model):
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    categoria = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.marca} {self.modelo} {self.color}"


class Auto(models.Model):
    marca = models.CharField(max_length=30)
    modelo = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.marca} ({self.modelo})"


############### pseudo0-instagram #############################


class Perfil(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=2200)

    def __str__(self):
        return f"{self.usuario}"


class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/posts", null=True, blank=True)
    epigrafe = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.epigrafe}"


class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.CharField(max_length=2200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"@{self.autor}: '{self.post}'"

AppCoder/forms.py
from django import forms


from .models import Avatar


class AutoFormulario(forms.Form):
    Marca = forms.CharField()
    Modelo = forms.CharField()


class AutoBuscarFormulario(forms.Form):
    Marca = forms.CharField()


class MarcaFormulario(forms.Form):
    Marca = forms.CharField()
    Modelo = forms.CharField()
    Color = forms.CharField()
    Categoria = forms.CharField()


#### CLASE 23: registro

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserModel


class UserCreationFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = UserModel
        fields = ["password1", "password2", "username", "email"]
        help_texts = {k: "" for k in fields}


class UserEditionFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")

    class Meta:
        model = UserModel
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        help_texts = {k: "" for k in fields}


class UserAvatarFormulario(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ["imagen"]

AppCoder/views.py
from datetime import date

from django.shortcuts import redirect, render

from datetime import datetime
from . import models
from .models import Auto, Marca, Avatar

from .forms import AutoFormulario, AutoBuscarFormulario, MarcaFormulario, UserAvatarFormulario

from django.contrib.auth.decorators import login_required

def inicio_view(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""

    return render(request, "AppCoder/inicio.html", context={"avatar_url": avatar_url})


def autos_buscar_view(request):
    if request.method == "GET":
        form = AutoBuscarFormulario()
        return render(
            request,
            "AppCoder/curso_formulario_busqueda.html",
            context={"form": form}
        )
    else:
        formulario = AutoBuscarFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            cursos_filtrados = []
            for auto in auto.objects.filter(auto=informacion["auto"]):
                cursos_filtrados.append(auto)

            contexto = {"autos": cursos_filtrados}
            return render(request, "AppCoder/autos_list.html", contexto)


def autos_todos_view(request):
    todos_los_autos = []
    for auto in Auto.objects.all():
        todos_los_autos.append(auto)

    contexto = {"autos": todos_los_autos}
    return render(request, "AppCoder/autos_list.html", contexto)


def autos_view(request):
    if request.method == "GET":
        form = AutoFormulario()
        return render(
            request,
            "AppCoder/auto_formulario_avanzado.html",
            context={"form": form}
        )
    else:
        formulario = AutoFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            auto = Auto(marca=informacion["Marca"], modelo=informacion["Modelo"])
            auto.save()

        return redirect("AppCoder:inicio")


def profesores_view(xx):
    nombre = "Mariano Manuel"
    apellido = "Barracovich"
    ahora = datetime.now()
    diccionario = {
        'nombre': nombre,
        'apellido': apellido,
        "nacionalidad": "argentino",
        "hora": ahora,
        "ciudades_preferidas": ["Buenos Aires", "Lima", "San Pablo", "Trieste"]
    }  
    return render(xx, "AppCoder/padre.html", diccionario)


#### CRUD #####
@login_required
def marca_view(request):
    if request.method == "GET":
        return render(
            request,
            "AppCoder/profesor_formulario_avanzado.html",
            {"form": MarcaFormulario()}
        )
    else:
        formulario = MarcaFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            modelo = Marca(
                marca=informacion["marca"],
                modelo=informacion["modelo"],
                color=informacion["color"],
                categoria=informacion["categoria"]
            )
            modelo.save()
        return render(
            request,
            "AppCoder/inicio.html",
        )

@login_required
def marcas_crud_read_view(request):
    marcas = Marca.objects.all()
    return render(request, "AppCoder/marcas_lista.html", {"marcas": marcas})

@login_required
def marcas_crud_delete_view(request, profesor_email):
    profesor_a_eliminar = Marca.objects.filter(email=profesor_email).first()
    profesor_a_eliminar.delete()
    return marcas_crud_read_view(request)

@login_required
def profesores_crud_update_view(request, profesor_email):
    marca = Marca.objects.filter(email=profesor_email).first()
    if request.method == "GET":
        formulario = MarcaFormulario(
            initial={
                "marca": marca.marca,
                "modelo": marca.modelo,
                "color": marca.color,
                "categoria": marca.categoria,
            }
        )
        return render(request, "AppCoder/marcas_formulario_edicion.html", {"form": formulario, "marca": marca})
    else:
        formulario = MarcaFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            marca.marca=informacion["marca"]
            marca.modelo=informacion["modelo"]
            marca.color=informacion["color"]
            marca.categoria=informacion["categoria"]
            marca.save()
        return marcas_crud_read_view(request)


from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


class AutoListView(LoginRequiredMixin, ListView):
    model = Auto
    context_object_name = "autos"
    template_name = "AppCoder/cbv_auto_list.html"


class AutoDetail(LoginRequiredMixin, DetailView):
    model = Auto
    template_name = "AppCoder/cbv_auto_detail.html"


class AutoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Auto
    template_name = "AppCoder/cbv_auro_create.html"
    success_url = reverse_lazy("AppCoder:auto-list")
    fields = ["marca", "modelo"]
    success_message = "Auto creado con éxito!" 

class AutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Auto
    template_name = "AppCoder/cbv_auto_update.html"
    success_url = reverse_lazy("AppCoder:auto-list")
    fields = ["marca"]

class AutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Auto
    template_name = "AppCoder/cbv_auto_delete.html"
    success_url = reverse_lazy("AppCoder:auto-list")



###Login / Logout 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse

def login_view(request):

    if request.user.is_authenticated:
        return render(
            request,
            "AppCoder/inicio.html",
            {"mensaje": f"Ya estás autenticado: {request.user.username}"}
        )

    if request.method == "GET":
        return render(
            request,
            "AppCoder/login.html",
            {"form": AuthenticationForm()}
        )
    else:
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            password = informacion["password"]

            modelo = authenticate(username=usuario, password=password)
            login(request, modelo)

            return render(
                request,
                "AppCoder/inicio.html",
                {"mensaje": f"Bienvenido {modelo.username}"}
            )
        else:
            return render(
                request,
                "AppCoder/login.html",
                {"form": formulario}
            )



def logout_view(request):
    logout(request)
    
    return redirect(reverse("AppCoder/logout"))

from .forms import UserCreationFormulario, UserEditionFormulario
from django.contrib.auth.views import PasswordChangeView


def registro_view(request):

    if request.method == "GET":
        return render(
            request,
            "AppCoder/registro.html",
            {"form": UserCreationFormulario()}
        )
    else:
        formulario = UserCreationFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            formulario.save()

            return render(
                request,
                "AppCoder/inicio.html",
                {"mensaje": f"Usuario creado: {usuario}"}
            )
        else:
            return render(
                request,
                "AppCoder/registro.html",
                {"form": formulario}
            )

### Editar perfil 

@login_required
def editar_perfil_view(request):

    usuario = request.user
    avatar = Avatar.objects.filter(user=usuario).last()
    avatar_url = avatar.imagen.url if avatar is not None else ""


    if request.method == "GET":


        valores_iniciales = {
            "email": usuario.email,
            "first_name": usuario.first_name,
            "last_name": usuario.last_name
        }


        formulario = UserEditionFormulario(initial=valores_iniciales)
        return render(
            request,
            "AppCoder/editar_perfil.html",
            context={"form": formulario, "usuario": usuario, "avatar_url": avatar_url}
            )
    else:
        formulario = UserEditionFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data

            usuario.email = informacion["email"]

            usuario.set_password(informacion["password1"])

            usuario.first_name = informacion["first_name"]
            usuario.last_name = informacion["last_name"]
            usuario.save()
        return redirect("AppCoder:inicio")


@login_required
def crear_avatar_view(request):

    usuario = request.user

    if request.method == "GET":
        formulario = UserAvatarFormulario()
        return render(
            request,
            "AppCoder/crear_avatar.html",
            context={"form": formulario, "usuario": usuario}
        )
    else:
        formulario = UserAvatarFormulario(request.POST, request.FILES)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            modelo = Avatar(user=usuario, imagen=informacion["imagen"])
            modelo.save()
            return redirect("AppCoder:inicio")

AppCoder/templates/AppCoder/auto_formulario_avanzado.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
<style>
    .form-container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 20px;
        box-shadow: 0 6px 10px rgba(0, 0, 0, 0.25);
        width: 40%;
        margin: 60px auto;
        text-align: left;
    }

    .form-container h2 {
        margin-bottom: 20px;
        color: #ff8787;
    }

    table {
        margin: 60px auto;
        border-collapse: separate;
        border-spacing: 0 15px;
    }

    th {
        text-align: left;
        padding-left: 15px;
    }

    td {
        background-color: #f2f2f2;
        border-radius: 5px;
    }

    input[type="text"], input[type="number"], input[type="email"], select {
        width: 90%;
        padding: 10px;
        margin: 5px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
        border-radius: 5px;
    }

    input[type="submit"] {
        background-color: #ff0000;
        color: white;
        border: none;
        padding: 15px 30px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #ff8787;
    }
</style>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Formulario</title>
    </head>

    <body style="background-color: white;">
        <div class="form-container">
            <form action="/AppCoder/autos/" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Guardar">
            </form>
        </div>
    </body>

    </html>
{% endblock %}

AppCoder/templates/AppCoder/cbv_auto_list.html
{% extends "AppCoder/padre.html" %}

{% block contenidoQueCambia %}
<!-- y todo esto para darle estilo (color, fuente, etc.) -->
<style>
    .messages {
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
    }

    .info, .success {
        color: #3c763d;
        background-color: #dff0d8;
        border-color: #d6e9c6;
    }

    .warning {
        color: #8a6d3b;
        background-color: #fcf8e3;
        border-color: #faebcc;
    }

    .error {
        color: #a94442;
        background-color: #f2dede;
        border-color: #ebccd1;
    }

    .messages li {
        margin: 5px 0;
        padding: 5px;
    }
</style>

<!-- Agregué esto para el mensaje -->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; max-width: 600px; margin: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <h4 style="color: #4a90e2; border-bottom: 2px solid #4a90e2; padding-bottom: 10px;">Lista de autos</h4>

    <!-- Button for "Create Auto" -->
    <button style="background-color: #4CAF50; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-bottom: 15px;">
        <a href="{% url 'AppCoder:auto-create' %}" style="color: white;">Nuevo</a>
    </button>

    <div style="margin-top: 20px;">
    {% for auto in autos %}
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h6 style="color: #333; background-color: #eaf2ff; padding: 8px; border-radius: 5px; margin-bottom: 10px; flex-grow: 1;">
                {{auto.marca}} ({{auto.modelo}})
            </h6>
            <div>
                <button style="background-color: #4a90e2; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
                    <a href="{% url 'AppCoder:auto-update' auto.pk %}" style="color: white;">Editar</a>
                </button>
                <button style="background-color:  #FF5733; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
                    <a href="{% url 'AppCoder:auto-delete' auto.pk %}" style="color: white;">Eliminar</a>
                </button>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

AppCoder/templates/AppCoder/cbv_auto_update.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}

<style>
    .form-container {
        background-color: white;
        padding: 40px;
        border-radius: 15px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 50%;
        margin: 50px auto;
        text-align: center;
    }

    .form-container h2 {
        margin-bottom: 20px;
        color: #4CAF50; /* A green color to match the theme */
    }

    .form-field {
        margin-bottom: 15px;
    }

    input[type="submit"] {
        background-color: #4CAF50; /* A green color to match the theme */
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="form-container">
    <h2>Editar auto</h2>
    <form action="{% url 'AppCoder:auto-update' auto.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-field">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Editar">
    </form>
</div>

{% endblock%}

AppCoder/templates/AppCoder/cbv_curso_delete.html
{% extends "AppCoder/padre.html" %}

{% block contenidoQueCambia %}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .warning-message {
        background-color: #ffcccb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 20px;
    }

    .warning-message h1 {
        color: red;
    }

    .warning-message p {
        font-size: 18px;
    }

    .submit-button {
        background-color: red;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="centered-container">
    {{ nombre }}
    <div class="warning-message">
        <h1>Borrar Curso: {{curso.curso}}</h1>
        <p>Estás seguro que deseas borrar el curso: <strong>{{curso.curso}}</strong> - camada: <strong>{{ curso.camada }}</strong>?</p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar" class="submit-button">
    </form>
</div>

{% endblock %}

AppCoder/templates/AppCoder/cbv_curso_detail.html
{% extends "AppCoder/padre.html" %}
{% block contenidoQueCambia %}
<style>
    body {
        font-family: Arial, sans-serif;
    }
    h1 {
        color: navy;
        text-align: center;
    }
    .curso-details {
        background-color: lightgray;
        padding: 20px;
        border-radius: 8px;
        text-align: center;
    }
    a {
        background-color: blue;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        display: inline-block;
        margin-top: 20px;
    }
    a:hover {
        background-color: darkblue;
    }
</style>

<div class="curso-details">
    <p>{{ nombre }}</p>
    <h1>Detalle del curso</h1>
    <p>{{ curso.curso }} - camada: {{ curso.camada }}</p>
    <a href="{% url 'AppCoder:curso-list' %}">Regresar</a>
</div>

{% endblock %}

AppCoder/templates/AppCoder/cbv_curso_list.html
{% extends "AppCoder/padre.html" %}

{% block contenidoQueCambia %}
<!-- y todo esto para darle estilo (color, fuente, etc.) -->
<style>
    .messages {
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
    }

    .info, .success {
        color: #3c763d;
        background-color: #dff0d8;
        border-color: #d6e9c6;
    }

    .warning {
        color: #8a6d3b;
        background-color: #fcf8e3;
        border-color: #faebcc;
    }

    .error {
        color: #a94442;
        background-color: #f2dede;
        border-color: #ebccd1;
    }

    .messages li {
        margin: 5px 0;
        padding: 5px;
    }
</style>

<!-- Agregué esto para el mensaje -->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; max-width: 600px; margin: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <h4 style="color: #4a90e2; border-bottom: 2px solid #4a90e2; padding-bottom: 10px;">Lista de cursos</h4>

    <!-- Button for "Create Curso" -->
    <button style="background-color: #4CAF50; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-bottom: 15px;">
        <a href="{% url 'AppCoder:curso-create' %}" style="color: white;">Nuevo</a>
    </button>

    <div style="margin-top: 20px;">
    {% for curso in cursos %}
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h6 style="color: #333; background-color: #eaf2ff; padding: 8px; border-radius: 5px; margin-bottom: 10px; flex-grow: 1;">
                {{curso.curso}} ({{curso.camada}})
            </h6>
            <div>
                <button style="background-color: #4a90e2; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
                    <a href="{% url 'AppCoder:curso-update' curso.pk %}" style="color: white;">Editar</a>
                </button>
                <button style="background-color:  #FF5733; color: white; padding: 8px 12px; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
                    <a href="{% url 'AppCoder:curso-delete' curso.pk %}" style="color: white;">Eliminar</a>
                </button>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

AppCoder/templates/AppCoder/crear_avatar.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}
<!DOCTYPE html>
 <html lang="en">

 <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; max-width: 600px; margin: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">

    <h6 style="color: #4a90e2; border-bottom: 2px solid #4a90e2; padding-bottom: 10px;">
        Crear avatar para: {{ usuario }}
    </h6>

    <div style="margin-top: 20px; background-color: white; padding: 20px; border-radius: 5px;">
        <form action="/AppCoder/crear-avatar" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Guardar" style="background-color: #4a90e2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
        </form>

    </div>

</div>
{% endblock%}

AppCoder/templates/AppCoder/inicio.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}

<h3>SOBRE NOSOTROS</h3>
Bienvenidos a HASCAR somo un concecionario con mas de 15 años de experiencia en la comecializacion de autos de alta gama. Contamos con dos sedes una en Puerto madero y otra en el barrio de Olivos

{{ mensaje }}
{% endblock %}

AppCoder/templates/AppCoder/login.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia %}

<h2>Login</h2>
<body style="background-color: rgb(134, 185, 245);">
    <form action="/AppCoder/login" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Iniciar sesión">
    </form>
</body>

{% endblock %}

AppCoder/templates/AppCoder/logout.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}
<h2>Te has deslogeado</h2>
{% endblock%}